<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_GeneralllllllyMembersSpace Details1 Mah_eca00c</name>
   <tag></tag>
   <elementGuidId>b8a853e9-cac3-4e32-99af-4a51f66c3698</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mantine-Paper-root.mantine-Modal-modal.mantine-l0ham1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mantine-w00wm87w2']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>611ffd08-3d32-44d2-8069-055641e5998b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-Paper-root mantine-Modal-modal mantine-l0ham1</value>
      <webElementGuid>01e554b0-051f-459d-a81a-606c4ef360b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>e6e8cf96-5360-49c7-a438-4fe19ecc6be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mantine-w00wm87w2-title</value>
      <webElementGuid>d155d4cd-315a-4f62-bb1d-d23f8fbb18ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>mantine-w00wm87w2-body</value>
      <webElementGuid>e4edb652-ac88-4e8e-b287-fb1a40224b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>644abda7-9d47-44e0-8f81-004428c82d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a8e0807b-9f6a-489c-80e6-b08299de192e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GeneralllllllyMembersSpace Details1 Maharj@nsumeetramhrjn123@gmail.comSSumitra Maharjansumeetramhrjn@gmail.comAdd People *Add to space</value>
      <webElementGuid>b3749a4f-2785-4a6d-8a54-de42f6795c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-w00wm87w2&quot;)/div[@class=&quot;mantine-16pg774 mantine-Modal-inner&quot;]/div[@class=&quot;mantine-Paper-root mantine-Modal-modal mantine-l0ham1&quot;]</value>
      <webElementGuid>ceef0b20-6629-4cdd-a2a2-63aed69ac57c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mantine-w00wm87w2']/div/div</value>
      <webElementGuid>67436011-b615-4558-ba5b-fac63ef7172f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nov 14, 2022 2:47 PM'])[1]/following::div[37]</value>
      <webElementGuid>8ea0a336-f83c-4d5a-a5a7-112f4eed77fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div</value>
      <webElementGuid>d06c1659-db64-4e06-a411-067db31e68a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'GeneralllllllyMembersSpace Details1 Maharj@nsumeetramhrjn123@gmail.comSSumitra Maharjansumeetramhrjn@gmail.comAdd People *Add to space' or . = 'GeneralllllllyMembersSpace Details1 Maharj@nsumeetramhrjn123@gmail.comSSumitra Maharjansumeetramhrjn@gmail.comAdd People *Add to space')]</value>
      <webElementGuid>0e4a669c-79cc-4ae9-8453-f2b0a7d12c9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
