<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Members</name>
   <tag></tag>
   <elementGuidId>e2445232-cf86-4b60-a2f5-c0a69aff077a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mantine-Tabs-tabControl.mantine-Tabs-default.mantine-Group-child.mantine-52n0vt > div.mantine-rdtd06.mantine-Tabs-tabInner > div.mantine-1s8spa1.mantine-Tabs-tabLabel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mantine-w00wm87w2-body']/div/div/div/div/button/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3ed721db-911a-41cc-93b8-968cc602d49a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-1s8spa1 mantine-Tabs-tabLabel</value>
      <webElementGuid>d9e9f05b-cb17-42df-8100-6e68402c780f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Members</value>
      <webElementGuid>c9779a24-6700-428a-b90c-a4c3309c1f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-w00wm87w2-body&quot;)/div[1]/div[@class=&quot;mantine-Tabs-root mantine-jjhffj&quot;]/div[@class=&quot;mantine-Tabs-tabsListWrapper mantine-Tabs-default mantine-1u25t5n&quot;]/div[@class=&quot;mantine-Group-root __mantine-ref-tabsList mantine-Tabs-tabsList mantine-1tggmaq&quot;]/button[@class=&quot;mantine-Tabs-tabControl mantine-Tabs-default mantine-Group-child mantine-52n0vt&quot;]/div[@class=&quot;mantine-rdtd06 mantine-Tabs-tabInner&quot;]/div[@class=&quot;mantine-1s8spa1 mantine-Tabs-tabLabel&quot;]</value>
      <webElementGuid>083d018c-89f2-4c62-a96a-2510cd34ca7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mantine-w00wm87w2-body']/div/div/div/div/button/div/div</value>
      <webElementGuid>2555bb02-36d2-4b21-aff1-f5596e4b8e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generallllllly'])[3]/following::div[7]</value>
      <webElementGuid>a655b003-b798-436f-bcdc-f86b5e32a950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Space Details'])[1]/preceding::div[1]</value>
      <webElementGuid>663516f4-08db-4e61-80fb-4bd6f406f5e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/button/div/div</value>
      <webElementGuid>8e6945ec-5f04-4d5c-b386-289a1c5dc71a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Members' or . = 'Members')]</value>
      <webElementGuid>61822dbe-2fb5-4704-9101-992c5bf87c92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
