<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Create an account</name>
   <tag></tag>
   <elementGuidId>a322b9bd-5710-45cf-a3f1-286bc9831d9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mantine-Button-outline.mantine-Button-root.mantine-13o4935</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5b9307a1-ac28-459d-8e04-bd1940ed9ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-Button-outline mantine-Button-root mantine-13o4935</value>
      <webElementGuid>964bf048-2705-49fb-a38a-082308447b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>53b4ef76-ad4a-4916-bf7d-59b351ce0416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create an account</value>
      <webElementGuid>ec7f4538-3442-472f-bdea-225497895ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/nav[@class=&quot;py-lg&quot;]/div[@class=&quot;nav-items flex full-width&quot;]/div[@class=&quot;links-area flex&quot;]/div[@class=&quot;nav-item ml-md&quot;]/button[@class=&quot;mantine-Button-outline mantine-Button-root mantine-13o4935&quot;]</value>
      <webElementGuid>e6821b5a-4e3a-422e-916b-ad01f6b90afa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[3]</value>
      <webElementGuid>7674a7cd-fb44-49e3-8017-4fc0f9d09d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/nav/div/div[2]/div[4]/button</value>
      <webElementGuid>341e23c7-ccac-40f5-8ad6-1703d379c5a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/following::button[1]</value>
      <webElementGuid>e0a5e648-06bc-45d6-b85f-01a9e0ae9d76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::button[2]</value>
      <webElementGuid>85c57864-27e5-4bf8-8193-246285fa5640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='One Stop For Your Entire Team'])[1]/preceding::button[1]</value>
      <webElementGuid>2f93aead-a69c-486e-9c99-ef492b9b91c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>a47b8518-393e-4851-a579-71dce387aa13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Create an account' or . = 'Create an account')]</value>
      <webElementGuid>473d6705-69a6-4caf-ae50-5cc27e91af8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
