<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Password_Field</name>
   <tag></tag>
   <elementGuidId>54cdbafe-1107-4a45-9a83-92cb8aa1958d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mantine-iv0w6dfxs</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mantine-iv0w6dfxs']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0515636d-5c99-424f-adb0-9aa1bddc425b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>8d6a34f6-654b-4ee2-98f1-3d267e5b5a75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-164y8ej mantine-PasswordInput-innerInput</value>
      <webElementGuid>e7542dff-d4d0-40a5-9aca-2b2a2fa15e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mantine-iv0w6dfxs</value>
      <webElementGuid>6836fc9b-810b-4cf8-ae1a-f4daa25ba8c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your password</value>
      <webElementGuid>8769b342-3749-48ee-a8db-39b80740e464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>t</value>
      <webElementGuid>b28e1cec-a9ad-45e4-9835-633ed8e4fb28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-iv0w6dfxs&quot;)</value>
      <webElementGuid>1095a443-7149-4015-a249-c9c546dfbf0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mantine-iv0w6dfxs']</value>
      <webElementGuid>193fe85d-2e5c-4ba8-ad80-f8412d1980b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/div[3]/form/div[2]/div/div/input</value>
      <webElementGuid>4331d0c1-b85a-47e0-81f2-c78205e7c9c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>55dbcbad-b91b-46a7-95f0-05aade482153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'mantine-iv0w6dfxs' and @placeholder = 'Enter your password']</value>
      <webElementGuid>1fb3c759-7ac9-48ab-be2f-aa3ccc87f728</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
