<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>QA_Option</name>
   <tag></tag>
   <elementGuidId>9e6475f0-d10c-465d-a8c0-ddc1c19c3341</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mantine-Menu-item.mantine-Menu-itemHovered.mantine-1dlvs06 > div.mantine-1ho4z9l.mantine-Menu-itemInner > div.mantine-105ajhz.mantine-Menu-itemBody</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mantine-gkea3w0oo']/div[2]/div[2]/button/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bba32278-21ee-4fcf-be5e-ae39e5d07f7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-105ajhz mantine-Menu-itemBody</value>
      <webElementGuid>46d4ab8b-ad70-448a-894b-6df865580739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>QQA</value>
      <webElementGuid>698b8069-022c-499e-bbfb-2eba7f1a00f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-gkea3w0oo&quot;)/div[@class=&quot;organizations-list&quot;]/div[2]/button[@class=&quot;mantine-Menu-item mantine-Menu-itemHovered mantine-1dlvs06&quot;]/div[@class=&quot;mantine-1ho4z9l mantine-Menu-itemInner&quot;]/div[@class=&quot;mantine-105ajhz mantine-Menu-itemBody&quot;]</value>
      <webElementGuid>aed0299b-6f77-4f9d-9516-237603a575c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mantine-gkea3w0oo']/div[2]/div[2]/button/div/div</value>
      <webElementGuid>8abd8d1d-0f9a-4dc5-8504-4e5d3f9b7747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test123'])[2]/following::div[3]</value>
      <webElementGuid>67edebdc-714e-4ded-b700-9ece03b1f8ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='T'])[1]/following::div[4]</value>
      <webElementGuid>e338fa1c-7ef4-45c2-b40e-4f10052762d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/div/div</value>
      <webElementGuid>a5beebd8-a1cf-4bf5-a785-f6f7c9255fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'QQA' or . = 'QQA')]</value>
      <webElementGuid>83aca480-71e9-4ebe-97b4-16087cbe101f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
