<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Meet (Beta)</name>
   <tag></tag>
   <elementGuidId>b191a805-722c-449b-81f9-068c7e679d9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mantine-Tabs-tabControl.mantine-Tabs-pills.mantine-Group-child.tab.pt-4.pb-6.mantine-1o6esa1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c28d0cd8-e30b-4246-b181-ce2f3e763d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-Tabs-tabControl mantine-Tabs-pills mantine-Group-child tab pt-4 pb-6 mantine-1o6esa1</value>
      <webElementGuid>983c5797-f311-4a2c-9a11-e2e2293d3c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>64dcde3b-e11f-43cd-bf4b-67572e2e117a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2c63da5a-60f9-4d79-b5ff-9fcc5e3f4eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>84107eea-b9ff-49d8-b5fb-c09d75bed263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>caf787d2-41fd-4ef1-b491-19eeb03e5ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Meet (Beta)</value>
      <webElementGuid>52d0362b-e418-4e3d-bd3c-17ccc8db96c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app-desktop&quot;]/div[@class=&quot;flex full-width&quot;]/div[@class=&quot;flex full-width relative&quot;]/section[@class=&quot;flex column full-width px-md pb-sm&quot;]/div[@class=&quot;mantine-Group-root flex justify-between full-width fill-height mantine-6y1794&quot;]/div[@class=&quot;mantine-Tabs-root mantine-Group-child full-width full-height flex column mantine-leqxg4&quot;]/div[@class=&quot;mantine-Tabs-tabsListWrapper mantine-Tabs-pills mantine-18v8a5v&quot;]/div[@class=&quot;mantine-Group-root __mantine-ref-tabsList mantine-Tabs-tabsList mantine-1wh8mct&quot;]/button[@class=&quot;mantine-Tabs-tabControl mantine-Tabs-pills mantine-Group-child tab pt-4 pb-6 mantine-1o6esa1&quot;]</value>
      <webElementGuid>424a8261-ed56-4674-9c60-88c0406fb378</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>69568e90-deb2-44e3-8da5-e0206db455ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/section/div/div/div/div/button[2]</value>
      <webElementGuid>f0542c55-3c56-4227-9d84-cc111a21b918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chat'])[1]/following::button[1]</value>
      <webElementGuid>a43fe72a-cd65-44f1-8c6a-628970ecfec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sumeetramhrjn@gmail.com'])[1]/following::button[2]</value>
      <webElementGuid>c6362a4c-d135-4d83-9f9b-f2f52030a63a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shared Files'])[1]/preceding::button[1]</value>
      <webElementGuid>1638500d-8c7b-459d-bf8c-55cc7859e924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>c1d10402-eedb-4564-a3ce-5ae80906277d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Meet (Beta)' or . = 'Meet (Beta)')]</value>
      <webElementGuid>a189444a-9870-428d-97f4-5a9292930ba1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
