<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Shared Photos</name>
   <tag></tag>
   <elementGuidId>80368a56-548c-43da-bf72-6393fa28b0e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d13449ac-7bae-43dd-aa15-f6d050b2176b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-Tabs-tabControl mantine-Tabs-outline mantine-Group-child tab pt-4 pb-6 mantine-16pkli</value>
      <webElementGuid>c298b70b-aacd-4f35-a941-04ff8cc05d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a76e9802-356c-4b69-b7e1-31ba7e478e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>25fbd0d0-2cc0-4cda-bcbb-ecc5af4aba27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>4b435a34-5097-499e-95ff-fb0b0b01ee47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2d58745a-c537-4071-95ad-2bfc03e8fe83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shared Photos</value>
      <webElementGuid>e8f6dd93-2858-4f63-bea2-9fb6614f06ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app-desktop&quot;]/div[@class=&quot;flex full-width&quot;]/div[@class=&quot;flex full-width relative&quot;]/section[@class=&quot;flex column full-width px-md pb-sm&quot;]/div[@class=&quot;mantine-Group-root flex justify-between full-width fill-height mantine-6y1794&quot;]/div[@class=&quot;mantine-Tabs-root mantine-Group-child full-width flex column mantine-leqxg4&quot;]/div[@class=&quot;mantine-Tabs-tabsListWrapper mantine-Tabs-outline mantine-jt4rky&quot;]/div[@class=&quot;mantine-Group-root __mantine-ref-tabsList mantine-Tabs-tabsList mantine-1tggmaq&quot;]/button[@class=&quot;mantine-Tabs-tabControl mantine-Tabs-outline mantine-Group-child tab pt-4 pb-6 mantine-16pkli&quot;]</value>
      <webElementGuid>3fc552b8-aac2-490a-852c-0f9c7056c821</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>e7f9c388-b34f-4543-96fe-8b0ba12c6444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/section/div/div/div/div/button[4]</value>
      <webElementGuid>1eed24e5-b699-4069-9bed-0129b54dff80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shared Files'])[1]/following::button[1]</value>
      <webElementGuid>bb362a7d-b359-4f5e-a5b3-98e18a3593c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meet (Beta)'])[1]/following::button[2]</value>
      <webElementGuid>8c71b3eb-b40e-4ea4-b853-cdb2b65bd340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Polls'])[1]/preceding::button[1]</value>
      <webElementGuid>3db42eee-2252-4e79-8f93-84b86f59459c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>ca22f4f2-df9d-42d1-ae11-c444b4b2f5e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Shared Photos' or . = 'Shared Photos')]</value>
      <webElementGuid>179cf7ba-bea5-407d-86ea-5f2cdf0b07c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
