<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Apply Changes_Button</name>
   <tag></tag>
   <elementGuidId>0ec6f2e9-aec8-4455-a815-c3b92bb745ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mantine-3xbgk5.mantine-Button-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div[2]/div[2]/div[2]/section/div/form/div[4]/button/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3a0e881a-a87d-4f4e-b962-2b838017d905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-3xbgk5 mantine-Button-inner</value>
      <webElementGuid>600d5d3d-273c-4e2d-b13d-978adcf3942e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Apply Changes</value>
      <webElementGuid>bf36d441-b542-4e9e-b9bb-f6237884e72b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app-desktop&quot;]/div[@class=&quot;flex full-width&quot;]/div[@class=&quot;h-[94vh] flex-1&quot;]/div[@class=&quot;mantine-Tabs-root h-[70%] mantine-944diq&quot;]/div[@class=&quot;mantine-1euen2d mantine-Tabs-body&quot;]/section[@class=&quot;py-xl pl-sm&quot;]/div[1]/form[1]/div[@class=&quot;mantine-Group-root mantine-ti75e8&quot;]/button[@class=&quot;mantine-Button-filled mantine-Button-root mantine-Group-child bg-secondary mantine-vv65v0&quot;]/div[@class=&quot;mantine-3xbgk5 mantine-Button-inner&quot;]</value>
      <webElementGuid>b18b4867-2b0f-4ae0-92bc-40a4d1ad8d89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/div[2]/div[2]/section/div/form/div[4]/button/div</value>
      <webElementGuid>d2818c45-ec31-47c9-8bdc-27832e5bf137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::div[3]</value>
      <webElementGuid>0305f316-02d1-490e-8952-15a283e12888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button/div</value>
      <webElementGuid>51f7cfd3-5f83-49a0-b4f2-7adb875e3640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Apply Changes' or . = ' Apply Changes')]</value>
      <webElementGuid>6750ab25-8cfa-4e87-ae79-285947928045</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
