<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Email_Disabled_Field</name>
   <tag></tag>
   <elementGuidId>5c2603ff-4e0d-455f-ba03-4c32e4398c7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mantine-pd4rew3cc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mantine-pd4rew3cc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d196f31d-99c0-4302-90a7-f816287c6ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>test123@yopmail.com</value>
      <webElementGuid>3fbe0d7a-0ca9-4822-8e7e-ab25b7cc685d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mantine-pd4rew3cc</value>
      <webElementGuid>578855da-a392-462b-9b58-38549cc26792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f21e8fd5-1cf4-4e68-8fc3-8a388a18a26b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1d169c27-0dfc-4bce-bb98-04ffc27bd032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-TextInput-defaultVariant mantine-TextInput-input mantine-TextInput-disabled mantine-1xoment</value>
      <webElementGuid>e188ccfd-d6e0-4e7b-9503-3b6279ea6a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-pd4rew3cc&quot;)</value>
      <webElementGuid>17d4310b-2e84-44f8-b183-fa285c266fb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mantine-pd4rew3cc']</value>
      <webElementGuid>53e440ef-29be-4cf6-88ed-ba8eddc0580d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/div[2]/div[2]/section/div/form/div[3]/div/input</value>
      <webElementGuid>6863eb35-1355-4929-ba8d-3a45d454344e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>cbb97adf-bc8f-4935-bbfe-8b2e3de8b3aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'test123@yopmail.com' and @id = 'mantine-pd4rew3cc' and @type = 'text']</value>
      <webElementGuid>48097230-0b66-46be-bda6-3163577ae0f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
