<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>First name_field</name>
   <tag></tag>
   <elementGuidId>e5652205-d1d2-47c4-a11e-5c43421b80ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mantine-w7y0ppgag</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mantine-w7y0ppgag']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ab9d54e-a7e5-4433-aa87-8bef4b5645e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>317a9405-2135-49da-883e-794b0f2d668a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your first name</value>
      <webElementGuid>065be91a-b2ab-4ad8-8933-41bcd2bb150e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mantine-w7y0ppgag</value>
      <webElementGuid>eef0a88c-d701-4f9e-9cbb-a1e57e38ec24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fb9a7263-5136-4455-af48-727272b39047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>420d9c66-792a-4a43-8a3b-42fd6f2c98be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-TextInput-defaultVariant mantine-TextInput-input mantine-1sm8in5</value>
      <webElementGuid>f73f13f5-0647-49e7-b4a6-70a73f470f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Test123</value>
      <webElementGuid>fc1381de-a1c8-4567-aa32-45819b364bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-w7y0ppgag&quot;)</value>
      <webElementGuid>54a8f053-69de-4230-8361-10a74f644c9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mantine-w7y0ppgag']</value>
      <webElementGuid>50a5245d-5078-4bb6-bfa6-cca5ae53396d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/div[2]/div[2]/section/div/form/div/div/div/input</value>
      <webElementGuid>a6afd1b6-63f6-44a1-ad59-079dc30bc707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9257e18c-abeb-43ec-89eb-abc12ad26b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter your first name' and @id = 'mantine-w7y0ppgag' and @type = 'text']</value>
      <webElementGuid>d4ff9a4e-9772-4dfe-855e-5fc321582c89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
