<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Phone_Field</name>
   <tag></tag>
   <elementGuidId>c4c03212-1963-4768-9574-6b3dba9382ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mantine-oi6bbp9ew</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mantine-oi6bbp9ew']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80ce23af-0fda-4fa2-b095-5939ca7d38d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your phone number</value>
      <webElementGuid>be35aa59-c095-4b45-ae29-3904dea77560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mantine-oi6bbp9ew</value>
      <webElementGuid>0d9887c6-3e35-4c2b-837a-5aacc15ec6f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>b1b9072e-f5a7-4767-a9b2-f3a8b0887282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>443fd672-6c02-48d1-b2c5-78d4fc2df964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-TextInput-defaultVariant mantine-TextInput-input mantine-1sm8in5</value>
      <webElementGuid>53a069a9-9c0b-494a-8e29-08abcac95489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>123</value>
      <webElementGuid>211684e6-b117-495e-92b6-0658ba125675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-oi6bbp9ew&quot;)</value>
      <webElementGuid>a4bfa190-024d-4980-a608-7729e9452084</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mantine-oi6bbp9ew']</value>
      <webElementGuid>636aa458-b25f-4719-8b0c-fc061424cd54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/div[2]/div[2]/section/div/form/div[2]/div/input</value>
      <webElementGuid>36b6fd17-2e73-4d36-889f-753c1fe96faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>fc2823f8-7d0a-4a55-848f-919fe5834301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter your phone number' and @id = 'mantine-oi6bbp9ew' and @type = 'number']</value>
      <webElementGuid>d59f806b-2133-4528-9b15-d3e42c60f9eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
