<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Username_img</name>
   <tag></tag>
   <elementGuidId>ce31457d-ccec-4f8f-88dc-989f86f8471c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.mantine-utvkm8.mantine-Image-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div[2]/div/div/div/figure/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a8bb345c-8d4c-4e5a-a5c0-2e518f775611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-utvkm8 mantine-Image-image</value>
      <webElementGuid>ab99e279-182b-4c2a-8d74-dcdd67906951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api-dev.daboospace.com/api/files/002d74cd5b83b7c0b12a09f80b4a71cf_thumb?path=organizations/63734b26b4c0b8002b889730/images</value>
      <webElementGuid>e5c4736d-9d61-4eca-a5b3-3365fa015c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>095a7af5-0a69-45cd-894f-498acf65ef8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;border-b-1 flex full-width py-sm&quot;]/div[@class=&quot;nav-items flex full-width justify-between px-lg&quot;]/div[@class=&quot;links-area flex items-center&quot;]/div[@class=&quot;nav-item flex-centered pointer&quot;]/div[@class=&quot;mantine-Menu-root mantine-193ey9s&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;mantine-Image-root mantine-15po0m8&quot;]/figure[@class=&quot;mantine-11nhzn5 mantine-Image-figure&quot;]/div[@class=&quot;mantine-qqmv3w mantine-Image-imageWrapper&quot;]/img[@class=&quot;mantine-utvkm8 mantine-Image-image&quot;]</value>
      <webElementGuid>96db75bb-9a63-42cb-aa03-ff3e23dffd49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/div/div/figure/div/img</value>
      <webElementGuid>1e6a5a76-532e-49a9-8099-8c8067e846b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='img']</value>
      <webElementGuid>8569a457-00ef-48a0-81df-463cb4eb577b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/div/img</value>
      <webElementGuid>62a10699-d725-48d8-9c3d-24bd9a2eaa1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api-dev.daboospace.com/api/files/002d74cd5b83b7c0b12a09f80b4a71cf_thumb?path=organizations/63734b26b4c0b8002b889730/images' and @alt = 'img']</value>
      <webElementGuid>986cfe2f-55e8-4da8-a292-648cccfb7c3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
