<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Email_Field</name>
   <tag></tag>
   <elementGuidId>2a77c6c0-df08-48da-af22-9664366473b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mantine-ax2h6cr90</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mantine-ax2h6cr90']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad2887e4-6c61-46ab-a767-d2aa46e7143b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your email</value>
      <webElementGuid>f5049f86-fd26-4fac-8873-b0eaa870fdf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mantine-ax2h6cr90</value>
      <webElementGuid>0e524635-ca91-47ae-8808-3b91c677d8f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>32335015-e139-4609-affc-3fdaaab694bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d3632a9b-c988-450a-a676-9ea8f1b3bc6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-TextInput-defaultVariant mantine-TextInput-input mantine-1sm8in5</value>
      <webElementGuid>1d990810-66a3-466e-8d5b-429eeec425df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>t</value>
      <webElementGuid>ffd23d68-bbd6-4cb5-9a9d-459192c1dba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-ax2h6cr90&quot;)</value>
      <webElementGuid>abdd9464-b1a6-41ca-85c3-4911c5fb1761</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mantine-ax2h6cr90']</value>
      <webElementGuid>70c42433-5964-447d-be7a-9315b7c1a1be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mantine-qgpl27w81-body']/form/div/div/input</value>
      <webElementGuid>05543e8b-c42f-48f6-9c6a-6bc0c89c6a1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div/div/input</value>
      <webElementGuid>e745b7e4-fa18-43d6-8dea-fbc65ec7ddb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter your email' and @id = 'mantine-ax2h6cr90' and @type = 'email']</value>
      <webElementGuid>c1df2ae1-11ac-483e-95da-ec7115c3b374</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
