<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm Password_mantine-ey040psgo</name>
   <tag></tag>
   <elementGuidId>b3740816-6700-444d-9a06-724d0dd855b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mantine-ey040psgo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mantine-ey040psgo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7864a91d-1156-4201-830e-e678acb29700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>1d4d452e-43b3-49b8-a234-25afc4c44008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-164y8ej mantine-PasswordInput-innerInput</value>
      <webElementGuid>b1ded039-7852-4fe3-ae39-8d62af5d3c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mantine-ey040psgo</value>
      <webElementGuid>fefbed60-855e-4e22-84ea-ecf98fb0f31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirm Password</value>
      <webElementGuid>c638e003-c8ba-47f6-9b0c-1b059fa91947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>T</value>
      <webElementGuid>f5bf23d2-52a1-415b-8213-4ca45cb36aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-ey040psgo&quot;)</value>
      <webElementGuid>92b56695-8e9e-49a1-b611-076339112deb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mantine-ey040psgo']</value>
      <webElementGuid>7acd47ff-8b9e-4707-915f-bb80395580ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/section/div/div/div[4]/form/div[3]/div/div/input</value>
      <webElementGuid>0f2db975-a563-4947-9072-39b8a3459dae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>684b7c23-267d-4f75-8511-1688b7d41651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'mantine-ey040psgo' and @placeholder = 'Confirm Password']</value>
      <webElementGuid>718fc5ee-c09c-441a-8ea5-52a7c34c9322</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
