<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_mantine-k4u6dvp5p</name>
   <tag></tag>
   <elementGuidId>7263f0c8-960f-4d33-b23a-1d69ad00bd63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mantine-k4u6dvp5p</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;mantine-k4u6dvp5p&quot;)[count(. | //input[@type = 'password' and @id = 'mantine-k4u6dvp5p' and @placeholder = 'Password']) = count(//input[@type = 'password' and @id = 'mantine-k4u6dvp5p' and @placeholder = 'Password'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mantine-k4u6dvp5p']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>92decba7-c97b-4ad5-a888-3680979fd1b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>1e4e129a-c074-4383-93de-0f50dbcd39ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-164y8ej mantine-PasswordInput-innerInput</value>
      <webElementGuid>14ec437d-5f1f-4a09-a3f8-5225635fc566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mantine-k4u6dvp5p</value>
      <webElementGuid>9634e893-6602-4e41-8505-119bdfa9acce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>8ebc95da-68b4-4a61-8a4e-11b59ec8b149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>T</value>
      <webElementGuid>afc2af05-85a2-4f86-b6c9-612e80e96346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-k4u6dvp5p&quot;)</value>
      <webElementGuid>8ceb7ace-c917-40da-bf9d-68652d22a01d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mantine-k4u6dvp5p']</value>
      <webElementGuid>cba9cc6f-0963-4300-9068-27e074c65c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/section/div/div/div[4]/form/div/div/div/input</value>
      <webElementGuid>22da7cb2-e845-4349-aa65-e174713f9dfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5ab409f6-8f18-42dd-9bb3-ec18c5f47763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'mantine-k4u6dvp5p' and @placeholder = 'Password']</value>
      <webElementGuid>f567903f-6e2d-4255-aaa9-846700ac217d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
