<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm Password_mantine-m8skv4nsk</name>
   <tag></tag>
   <elementGuidId>a5da1722-c73e-4b25-934a-aa995ba10f60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mantine-m8skv4nsk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mantine-m8skv4nsk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe904efa-a308-4f8f-a4bf-e37ed5b3ddad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>becfb896-1ae0-4f03-a42c-fdc031c1dfe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-164y8ej mantine-PasswordInput-innerInput</value>
      <webElementGuid>ef65eac8-bc68-43fd-9f0d-44d28b442bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mantine-m8skv4nsk</value>
      <webElementGuid>d214307d-1198-4156-b022-b50822d15e2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirm Password</value>
      <webElementGuid>586b208d-7781-4473-982e-53287222815c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>T</value>
      <webElementGuid>46457ad0-1cb3-4525-b40a-0c9d87d7a999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-m8skv4nsk&quot;)</value>
      <webElementGuid>3482b9e6-87fc-4a5b-88b2-1d14e4f6757f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mantine-m8skv4nsk']</value>
      <webElementGuid>7a690933-ae8e-4752-bab7-7c4af33a22fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/section/div/div/div[4]/form/div[3]/div/div/input</value>
      <webElementGuid>4d13eede-bf1e-494c-8ee6-6713601a17d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>13aca433-f68f-4554-9f34-85be28c86377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'mantine-m8skv4nsk' and @placeholder = 'Confirm Password']</value>
      <webElementGuid>8b9eec29-7df9-4c92-a69f-ba330cc05a58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
