<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>am_pm_option</name>
   <tag></tag>
   <elementGuidId>b9ef8767-c370-4c4a-990f-8ac54843e679</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.mantine-1azztlu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bde8ccb4-e3f7-4779-bade-9a30f3303701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5ef253aa-55e6-4100-88e3-d8366e9749ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-1azztlu</value>
      <webElementGuid>bdaa3258-4219-4117-bba1-d3f212e9fa4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>am</value>
      <webElementGuid>273861c7-e524-43de-b2d4-1274865276e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app-desktop&quot;]/div[@class=&quot;flex full-width&quot;]/div[@class=&quot;flex full-width relative&quot;]/section[@class=&quot;flex column full-width px-md pb-sm&quot;]/div[@class=&quot;mantine-Group-root flex justify-between full-width fill-height mantine-6y1794&quot;]/div[@class=&quot;mantine-Tabs-root mantine-Group-child full-width flex column mantine-leqxg4&quot;]/div[@class=&quot;mantine-1opdmpb mantine-Tabs-body&quot;]/div[@class=&quot;flat-card-3 h-[76vh] bg-stone-50&quot;]/div[@class=&quot;flex w-full h-full&quot;]/div[@class=&quot;w-8/12&quot;]/div[@class=&quot;form mt-xl&quot;]/form[1]/div[@class=&quot;flex mt-md&quot;]/div[@class=&quot;mantine-TimeInput-root ml-md mantine-z7oyte&quot;]/div[@class=&quot;mantine-TimeInput-wrapper mantine-12sbrde&quot;]/div[@class=&quot;mantine-TimeInput-defaultVariant mantine-TimeInput-input mantine-1sm8in5&quot;]/div[@class=&quot;mantine-x78oh3 mantine-TimeInput-controls&quot;]/input[@class=&quot;mantine-1azztlu&quot;]</value>
      <webElementGuid>1fb7a1cb-9535-4aee-a799-e1dbff5ddcca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[3]</value>
      <webElementGuid>4cfdb321-5f00-4beb-b22a-518d169432f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/section/div/div/div[2]/div/div/div/div[2]/form/div[2]/div[2]/div/div/div/input[3]</value>
      <webElementGuid>42ba3f9b-289a-4694-841f-ffce5a2718cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>bc8bd661-8305-4359-b5b8-34793ec7423a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'am']</value>
      <webElementGuid>7146d17e-037b-43df-a319-ba85dee04d67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
