<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Answer_Option2</name>
   <tag></tag>
   <elementGuidId>be1c26d0-a911-4b65-bd88-b36dfe5a7156</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mantine-zk29uq9np']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mantine-zk29uq9np</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b1edc32-2d33-4c4d-bb5f-2c5da86371bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Option 2</value>
      <webElementGuid>ba08ca0a-8ac3-458e-b935-0d4890a59106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mantine-zk29uq9np</value>
      <webElementGuid>baf90be0-3600-4861-88db-df18c934163b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>48b91302-912a-4bf3-8501-38db89977879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bdc9fad9-0fb5-4bff-81a3-d410413d02eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-TextInput-defaultVariant mantine-TextInput-input mantine-1sm8in5</value>
      <webElementGuid>1b36056a-f9ad-4fa3-a5b8-916db53e428c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-zk29uq9np&quot;)</value>
      <webElementGuid>93a7cd87-6be6-41c4-90fa-d5705d062d3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mantine-zk29uq9np']</value>
      <webElementGuid>03eb012f-6479-40c7-9dcd-665e8ba16dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/section/div/div/div[2]/div/div/div/div[2]/form/form/div[2]/div/div/input</value>
      <webElementGuid>1e1bf665-33ee-4d90-8134-852611fa9998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>f3658372-f28e-479a-98d3-4386c78e3189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Option 2' and @id = 'mantine-zk29uq9np' and @type = 'text']</value>
      <webElementGuid>36adc9d9-ea59-4374-938d-bc5832c54269</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
