<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Calendar</name>
   <tag></tag>
   <elementGuidId>67ca17a1-0c27-4e01-bdcd-6fabc38f7a19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[28]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>044e6053-d7d9-4a0f-8fde-c87fd16e79af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9d1282a9-b92a-43b4-ab4e-d3feb8b31bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0897f9d0-c6cc-4d89-b113-be42e6640843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-autofocus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>de52b622-5e2c-4a3e-9284-1a006c7ddd1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mantine-stop-propagation</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1e4fa05d-304c-4857-b8db-331d90e2123b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-hobli9 mantine-DatePicker-day</value>
      <webElementGuid>29b64bee-d509-4ffa-bd35-0d5d045b933a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>8db84516-db35-41a6-86ca-cc889befa11c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[10]/div[1]/div[1]/div[1]/div[@class=&quot;mantine-lsv3xl mantine-DatePicker-dropdownWrapper&quot;]/div[@class=&quot;mantine-Paper-root mantine-DatePicker-dropdown mantine-mrt426&quot;]/div[@class=&quot;mantine-DatePicker-calendarBase mantine-1nw5k7j&quot;]/div[1]/table[@class=&quot;mantine-DatePicker-month mantine-1tjz3wr&quot;]/tbody[1]/tr[3]/td[@class=&quot;mantine-157z7sm mantine-DatePicker-cell&quot;]/button[@class=&quot;mantine-hobli9 mantine-DatePicker-day&quot;]</value>
      <webElementGuid>b4a8750b-c13c-43d1-b4ec-0eb76a495809</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[28]</value>
      <webElementGuid>3e3b5e6f-bc2c-4f26-9d6c-1a9cdb2efabc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Su'])[1]/following::button[18]</value>
      <webElementGuid>d59c7ff0-90df-445e-af51-3db506035009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::button[18]</value>
      <webElementGuid>44fb28b6-6496-42f3-a9bd-47f7aa28817e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='17']/parent::*</value>
      <webElementGuid>96480f8f-39eb-45fd-b9c9-0c65291bfc47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/button</value>
      <webElementGuid>b6bee936-a731-4fdf-820d-1d49577bbb51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '17' or . = '17')]</value>
      <webElementGuid>975b93bd-f307-4a8c-af6c-c7266515816c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
