<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Active</name>
   <tag></tag>
   <elementGuidId>43fb92db-1fdc-475f-83eb-a81973c4a748</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div[2]/section/div/div/div[2]/div/div[2]/div/div/button/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mantine-Tabs-tabControl.mantine-Tabs-default.mantine-Group-child.mantine-52n0vt > div.mantine-rdtd06.mantine-Tabs-tabInner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>467e193e-7dac-4e46-86ab-3f3744da49b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-rdtd06 mantine-Tabs-tabInner</value>
      <webElementGuid>d180999e-2ea4-477f-bc05-bd1ef560897d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Active</value>
      <webElementGuid>dbaceff5-0a0c-432a-bc16-a816709b5411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app-desktop&quot;]/div[@class=&quot;flex full-width&quot;]/div[@class=&quot;flex full-width relative&quot;]/section[@class=&quot;flex column full-width px-md pb-sm&quot;]/div[@class=&quot;mantine-Group-root flex justify-between full-width fill-height mantine-6y1794&quot;]/div[@class=&quot;mantine-Tabs-root mantine-Group-child full-width flex column mantine-leqxg4&quot;]/div[@class=&quot;mantine-1opdmpb mantine-Tabs-body&quot;]/div[@class=&quot;flat-card-3 h-[76vh] bg-stone-50&quot;]/div[@class=&quot;mantine-Tabs-root h-[88%] mantine-jjhffj&quot;]/div[@class=&quot;mantine-Tabs-tabsListWrapper mantine-Tabs-default mantine-1u25t5n&quot;]/div[@class=&quot;mantine-Group-root __mantine-ref-tabsList mantine-Tabs-tabsList mantine-1tggmaq&quot;]/button[@class=&quot;mantine-Tabs-tabControl mantine-Tabs-default mantine-Group-child mantine-52n0vt&quot;]/div[@class=&quot;mantine-rdtd06 mantine-Tabs-tabInner&quot;]</value>
      <webElementGuid>4dc33b53-3fb9-4738-ba4f-91ff79994255</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/section/div/div/div[2]/div/div[2]/div/div/button/div</value>
      <webElementGuid>f3d3a95c-0ef2-41d1-a766-2d7f35269c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Create a Poll'])[1]/following::div[4]</value>
      <webElementGuid>91a886b8-8b8d-4251-83e1-71f5cef52020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Polls Status'])[1]/following::div[6]</value>
      <webElementGuid>83d0d0d1-9028-49a1-82d1-83ac422570a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drafts'])[1]/preceding::div[2]</value>
      <webElementGuid>513d1696-e6a0-43a6-af12-42a54c6b7ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button/div</value>
      <webElementGuid>9bd8b6b2-04bd-437c-a129-b9901b4cc3b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Active' or . = 'Active')]</value>
      <webElementGuid>7ddcb09d-c0c0-4626-8f6a-2537adc05043</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
