<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Drafts</name>
   <tag></tag>
   <elementGuidId>c3caf045-11c5-4720-8dec-dc464239877c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div[2]/section/div/div/div[2]/div/div[2]/div/div/button[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mantine-Tabs-tabControl.mantine-Tabs-default.mantine-Group-child.mantine-52n0vt > div.mantine-rdtd06.mantine-Tabs-tabInner > div.mantine-1s8spa1.mantine-Tabs-tabLabel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5ca3f8d3-b4cd-410d-91bd-54f8604bbbfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-1s8spa1 mantine-Tabs-tabLabel</value>
      <webElementGuid>efc88e60-c6d2-46a4-9e94-4b341a8371ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Drafts</value>
      <webElementGuid>9b200221-db2f-441d-ac9b-2361e0de099f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app-desktop&quot;]/div[@class=&quot;flex full-width&quot;]/div[@class=&quot;flex full-width relative&quot;]/section[@class=&quot;flex column full-width px-md pb-sm&quot;]/div[@class=&quot;mantine-Group-root flex justify-between full-width fill-height mantine-6y1794&quot;]/div[@class=&quot;mantine-Tabs-root mantine-Group-child full-width flex column mantine-leqxg4&quot;]/div[@class=&quot;mantine-1opdmpb mantine-Tabs-body&quot;]/div[@class=&quot;flat-card-3 h-[76vh] bg-stone-50&quot;]/div[@class=&quot;mantine-Tabs-root h-[88%] mantine-jjhffj&quot;]/div[@class=&quot;mantine-Tabs-tabsListWrapper mantine-Tabs-default mantine-1u25t5n&quot;]/div[@class=&quot;mantine-Group-root __mantine-ref-tabsList mantine-Tabs-tabsList mantine-1tggmaq&quot;]/button[@class=&quot;mantine-Tabs-tabControl mantine-Tabs-default mantine-Group-child mantine-52n0vt&quot;]/div[@class=&quot;mantine-rdtd06 mantine-Tabs-tabInner&quot;]/div[@class=&quot;mantine-1s8spa1 mantine-Tabs-tabLabel&quot;]</value>
      <webElementGuid>3559eb1a-5d32-41e4-b7d4-2deca44a237e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/section/div/div/div[2]/div/div[2]/div/div/button[2]/div/div</value>
      <webElementGuid>4cd64717-1467-48cd-ac6d-3272e17167a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/following::div[2]</value>
      <webElementGuid>c8f31f73-ae22-4073-b170-fb6476c2d831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Create a Poll'])[1]/following::div[7]</value>
      <webElementGuid>e6df2125-859e-42e2-a5b3-0e210220e68e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disabled'])[1]/preceding::div[1]</value>
      <webElementGuid>8a288e8e-799c-4207-9d01-bd8f4b54e06b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expired'])[1]/preceding::div[3]</value>
      <webElementGuid>da16d1b4-b55c-46c1-b5b3-6713b3874c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Drafts']/parent::*</value>
      <webElementGuid>8327e09e-1b03-45a6-acf6-eac3a0c5cbf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button[2]/div/div</value>
      <webElementGuid>7a069d0c-00c7-45f4-ba3d-a1e2c90a89ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Drafts' or . = 'Drafts')]</value>
      <webElementGuid>47147127-8d0e-431f-9cf3-130bf16716b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
