<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Poll End Date_date</name>
   <tag></tag>
   <elementGuidId>f73935f5-71fb-4c40-a519-43c44835dd11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mantine-ivcbyxx4e']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mantine-ivcbyxx4e</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>147ea9de-0829-4525-86e9-d8770793cfe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mantine-ivcbyxx4e</value>
      <webElementGuid>af7c6086-9f27-48de-823f-44440a4edd9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>7be9f2dd-841e-40df-b945-7e734d352a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Set poll end date</value>
      <webElementGuid>70f7c1dd-b536-4485-a3fd-35a10b894111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4fb18149-10f4-4ac4-ad5b-a8bd580d0bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>07b781fa-c142-4426-b894-110cbc0b5ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-DatePicker-defaultVariant mantine-DatePicker-input mantine-DatePicker-input mantine-19uv0yf</value>
      <webElementGuid>5961d8d6-215c-4e24-b950-ad9cd3edbd3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-ivcbyxx4e&quot;)</value>
      <webElementGuid>a45bbd1c-5128-4d90-a988-f1ba4fb9060b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mantine-ivcbyxx4e']</value>
      <webElementGuid>66cbe6d0-6a87-43ed-917f-487b782071ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/section/div/div/div[2]/div/div/div/div[2]/form/div[2]/div/div/div/div/input</value>
      <webElementGuid>2371896c-a021-40a4-9517-1da5fad19a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>138b6d23-c4f1-48a7-9c43-9f3bf5477922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mantine-ivcbyxx4e' and @name = 'date' and @placeholder = 'Set poll end date']</value>
      <webElementGuid>0d2c56fc-4ac8-4c21-90d6-5289d4482ffe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
