<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UserProfile</name>
   <tag></tag>
   <elementGuidId>8ce0da40-445a-4b65-af30-9d294564cf39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mantine-yiihbi.mantine-Avatar-placeholder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div[2]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ccdc106e-e25e-41c5-a1b9-22f4e39fb53e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-yiihbi mantine-Avatar-placeholder</value>
      <webElementGuid>e9404e43-a523-4bfc-bafa-9e581943b361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>T</value>
      <webElementGuid>d02fc582-d49c-4439-9617-3f778b2feded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;border-b-1 flex full-width py-sm&quot;]/div[@class=&quot;nav-items flex full-width justify-between px-lg&quot;]/div[@class=&quot;links-area flex items-center&quot;]/div[@class=&quot;nav-item flex-centered pointer&quot;]/div[@class=&quot;mantine-Menu-root mantine-193ey9s&quot;]/div[@class=&quot;flex ml-6&quot;]/div[@class=&quot;mantine-Avatar-root mantine-1i3wazg&quot;]/div[@class=&quot;mantine-yiihbi mantine-Avatar-placeholder&quot;]</value>
      <webElementGuid>8d9789eb-d03b-4622-89bb-c20b09c16017</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/div/div/div</value>
      <webElementGuid>a5dde92d-b34d-4db3-9571-fc03a0792661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test123 System'])[1]/preceding::div[1]</value>
      <webElementGuid>c4095ad8-2b5f-4fc4-9fc6-0d5dffd5c03e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USER'])[1]/preceding::div[2]</value>
      <webElementGuid>56b502b6-efe8-46b4-a9d3-a553b2385e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='T']/parent::*</value>
      <webElementGuid>40cfd169-f67c-449f-ab5e-5d128aaceef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div</value>
      <webElementGuid>d14aeb2f-21ef-4f41-afaa-86860d8bd379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'T' or . = 'T')]</value>
      <webElementGuid>885cb7fa-95ac-4108-a4a8-3fc9de9549fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
