<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_mantine-znwvxyn5i</name>
   <tag></tag>
   <elementGuidId>5295a0eb-f140-45e8-88f8-1e723dcceb1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mantine-znwvxyn5i</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mantine-znwvxyn5i']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b76d36cd-c8bf-4a11-8c7e-7d11e3463ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>2d874cfc-d582-404b-b49b-7d1897274423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-164y8ej mantine-PasswordInput-innerInput</value>
      <webElementGuid>1eb33327-867f-4235-b12b-08e7e92f4187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mantine-znwvxyn5i</value>
      <webElementGuid>b794fa95-9751-46ed-8cf3-053ff9bad3e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>3f787a8f-f501-4357-87db-7c4c60120456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>T</value>
      <webElementGuid>9237de42-fc26-425a-9cc9-bbcd2ba96b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-znwvxyn5i&quot;)</value>
      <webElementGuid>2d8e282b-0172-45a9-aaf5-1cffd5b09932</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mantine-znwvxyn5i']</value>
      <webElementGuid>9fa3f73a-3611-4890-a62a-7256c183a046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/section/div/div/div[4]/form/div/div/div/input</value>
      <webElementGuid>fdc2bc5c-5786-45af-98dd-274fca8503c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>31dd9834-f1f8-4485-b056-dbcace55020f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'mantine-znwvxyn5i' and @placeholder = 'Password']</value>
      <webElementGuid>8690af6b-41ac-469d-a002-c6358da08168</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
