<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Userprofile_img</name>
   <tag></tag>
   <elementGuidId>d797fe36-6313-4734-9275-cc8730569abd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mantine-Image-root.mantine-iat7s > figure.mantine-11nhzn5.mantine-Image-figure > div.mantine-qqmv3w.mantine-Image-imageWrapper > img.mantine-utvkm8.mantine-Image-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mantine-wkvnhv2qs']/button/div/div/div/div/div/figure/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3d90b5bf-9934-4907-beb0-c270289dcfa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-utvkm8 mantine-Image-image</value>
      <webElementGuid>8258eed9-89ad-4c64-8f43-d89a9b7261a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api-dev.daboospace.com/api/files/002d74cd5b83b7c0b12a09f80b4a71cf_thumb?path=organizations/63734b26b4c0b8002b889730/images</value>
      <webElementGuid>e03b3abe-07f8-4dc2-816f-29c59484e306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-wkvnhv2qs&quot;)/button[@class=&quot;mantine-Menu-item mantine-Menu-itemHovered mantine-1dlvs06&quot;]/div[@class=&quot;mantine-1ho4z9l mantine-Menu-itemInner&quot;]/div[@class=&quot;mantine-105ajhz mantine-Menu-itemBody&quot;]/div[@class=&quot;mantine-td3w39 mantine-Menu-itemLabel&quot;]/div[@class=&quot;flex items-center&quot;]/div[@class=&quot;mantine-Image-root mantine-iat7s&quot;]/figure[@class=&quot;mantine-11nhzn5 mantine-Image-figure&quot;]/div[@class=&quot;mantine-qqmv3w mantine-Image-imageWrapper&quot;]/img[@class=&quot;mantine-utvkm8 mantine-Image-image&quot;]</value>
      <webElementGuid>591b7325-cd8a-42ed-8092-37ec229b5989</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mantine-wkvnhv2qs']/button/div/div/div/div/div/figure/div/img</value>
      <webElementGuid>d5d17307-f2dd-4cc2-816a-006972a147ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://api-dev.daboospace.com/api/files/002d74cd5b83b7c0b12a09f80b4a71cf_thumb?path=organizations/63734b26b4c0b8002b889730/images')])[2]</value>
      <webElementGuid>d1561596-e2c1-4144-a81f-a62255d6c367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/div/div/div/div/figure/div/img</value>
      <webElementGuid>194c91dd-0e34-4315-9054-bec5c9769ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api-dev.daboospace.com/api/files/002d74cd5b83b7c0b12a09f80b4a71cf_thumb?path=organizations/63734b26b4c0b8002b889730/images']</value>
      <webElementGuid>f069df1e-e338-4465-9963-abd28b9351ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
