<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Username_img</name>
   <tag></tag>
   <elementGuidId>8466475e-f6d3-4050-b4cd-d6ac66278e81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.mantine-utvkm8.mantine-Image-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div[2]/div/div/div/figure/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d53ce034-57d8-40e2-8b9b-41cc8567e843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-utvkm8 mantine-Image-image</value>
      <webElementGuid>bde10397-1e18-4340-a335-877e388d2bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api-dev.daboospace.com/api/files/002d74cd5b83b7c0b12a09f80b4a71cf_thumb?path=organizations/63734b26b4c0b8002b889730/images</value>
      <webElementGuid>5c99c8ec-5eb4-4880-b9ca-fc25c063b442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>418552dd-15e1-4b06-beda-deb69abe314d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;border-b-1 flex full-width py-sm&quot;]/div[@class=&quot;nav-items flex full-width justify-between px-lg&quot;]/div[@class=&quot;links-area flex items-center&quot;]/div[@class=&quot;nav-item flex-centered pointer&quot;]/div[@class=&quot;mantine-Menu-root mantine-193ey9s&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;mantine-Image-root mantine-15po0m8&quot;]/figure[@class=&quot;mantine-11nhzn5 mantine-Image-figure&quot;]/div[@class=&quot;mantine-qqmv3w mantine-Image-imageWrapper&quot;]/img[@class=&quot;mantine-utvkm8 mantine-Image-image&quot;]</value>
      <webElementGuid>dc9f2549-bcce-43b3-a393-ceb8a0f28b65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/div/div/figure/div/img</value>
      <webElementGuid>930e9907-8112-4293-8101-48edaa5ab55e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='img']</value>
      <webElementGuid>cd7b3625-dd34-4883-800a-06fe88d95345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/div/img</value>
      <webElementGuid>d02a5920-bf9d-4736-91f3-bdda4a7947f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api-dev.daboospace.com/api/files/002d74cd5b83b7c0b12a09f80b4a71cf_thumb?path=organizations/63734b26b4c0b8002b889730/images' and @alt = 'img']</value>
      <webElementGuid>7e5697bd-a194-458f-bfe1-5ee4a2fcf9d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
