<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Generallllllly_pointer action-button</name>
   <tag></tag>
   <elementGuidId>c2b02664-457e-4f18-857b-088def1621f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.pointer.action-button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;root&quot;)/div[@class=&quot;app-desktop&quot;]/div[@class=&quot;flex full-width&quot;]/div[@class=&quot;flex full-width relative&quot;]/section[@class=&quot;flex column full-width px-md pb-sm&quot;]/header[1]/div[@class=&quot;mantine-Group-root flex justify-between full-width mantine-6y1794&quot;]/div[@class=&quot;mantine-gnzaph mantine-Group-child flex column py-sm&quot;]/div[@class=&quot;flex items-center&quot;]/svg[@class=&quot;pointer action-button&quot;][count(. | //svg[@class = 'pointer action-button' and @xmlns = 'http://www.w3.org/2000/svg']) = count(//svg[@class = 'pointer action-button' and @xmlns = 'http://www.w3.org/2000/svg'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Generallllllly'])[2]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>e554fdc7-19f2-4027-b0c2-334a467b31de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer action-button</value>
      <webElementGuid>086dcff2-4160-4bb5-be30-f8b8b5b35dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>b746bf77-02a2-4e6b-ae21-3d553a256d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>1f5a8d18-f7b9-428b-aa3e-850ea2f7cb98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>945f90b5-e6d6-437a-b194-47bb48d9ae64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>b57c36d7-3fe1-48f4-ab2f-7c5f771de56f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>22be7fd6-061d-4b5b-8445-93e0f5d2c3f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app-desktop&quot;]/div[@class=&quot;flex full-width&quot;]/div[@class=&quot;flex full-width relative&quot;]/section[@class=&quot;flex column full-width px-md pb-sm&quot;]/header[1]/div[@class=&quot;mantine-Group-root flex justify-between full-width mantine-6y1794&quot;]/div[@class=&quot;mantine-gnzaph mantine-Group-child flex column py-sm&quot;]/div[@class=&quot;flex items-center&quot;]/svg[@class=&quot;pointer action-button&quot;]</value>
      <webElementGuid>d95cb28d-f0f9-4af7-81ae-fcc1a1b45212</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generallllllly'])[2]/following::*[name()='svg'][1]</value>
      <webElementGuid>9bece89e-2582-4049-9a0b-a746d78c9e79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nice'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>965572aa-db99-4b89-b741-50afb535aa45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chat'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>90b9cc0a-5dcc-4144-a16c-a3ce3a3b781b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meet (Beta)'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>7c87b5aa-f363-40f8-b4f9-84a83ce1dce7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
