<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Apply_Changes_ButtonOrg</name>
   <tag></tag>
   <elementGuidId>0a4d9a5e-8689-4850-93b5-4ec3824842eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mantine-qo1k2.mantine-Button-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div[2]/div[2]/div[2]/section/div/form/div[3]/button/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>009da1e3-1482-4abe-8043-a0dbe1c19e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-qo1k2 mantine-Button-label</value>
      <webElementGuid>bd90edfe-1050-4060-8f5e-9e1d0d3a5370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply Changes</value>
      <webElementGuid>7291175a-c5ec-42c0-a4c0-ed2f23a32d6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app-desktop&quot;]/div[@class=&quot;flex full-width&quot;]/div[@class=&quot;h-[94vh] flex-1&quot;]/div[@class=&quot;mantine-Tabs-root h-[70%] mantine-944diq&quot;]/div[@class=&quot;mantine-1euen2d mantine-Tabs-body&quot;]/section[@class=&quot;py-xl pl-sm&quot;]/div[1]/form[1]/div[@class=&quot;mantine-Group-root mantine-ti75e8&quot;]/button[@class=&quot;mantine-Button-filled mantine-Button-root mantine-Group-child bg-secondary mantine-vv65v0&quot;]/div[@class=&quot;mantine-3xbgk5 mantine-Button-inner&quot;]/span[@class=&quot;mantine-qo1k2 mantine-Button-label&quot;]</value>
      <webElementGuid>e0aa5daa-569e-43d1-bd87-02e1f80d75a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/div[2]/div[2]/section/div/form/div[3]/button/div/span</value>
      <webElementGuid>c17568c8-1ad4-4c2e-9261-47e2c6cb273c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Official Profile'])[1]/following::span[2]</value>
      <webElementGuid>83ac398c-2cc3-411e-a3d5-d4e502cf76fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apply Changes']/parent::*</value>
      <webElementGuid>c3fcc2e3-2241-450a-82fe-a4fe798769cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>2617bccc-2998-4e65-abab-df8e504d0916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Apply Changes' or . = 'Apply Changes')]</value>
      <webElementGuid>774b6fb0-ef0a-46f1-b125-e72c0c10dd58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
