<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Email_Disabled_Field</name>
   <tag></tag>
   <elementGuidId>ab1ad345-4cba-41ac-8720-76f19aed422b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mantine-rybb1xhle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mantine-rybb1xhle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b5e7eb1-4840-44f0-ae8d-62a609081150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>test123@yopmail.com</value>
      <webElementGuid>d3e4e8a1-f74b-4dd7-ab8a-8747cfefa385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mantine-rybb1xhle</value>
      <webElementGuid>f1be9ec0-0ab5-4d1c-bd0b-505fbc82f080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9b0c4255-ac1a-4923-a861-e04dc4718236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6e533d42-24c6-4a76-98f3-8ddf17000b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-TextInput-defaultVariant mantine-TextInput-input mantine-TextInput-disabled mantine-1xoment</value>
      <webElementGuid>0c00dcfb-e580-436e-befc-408117739259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-rybb1xhle&quot;)</value>
      <webElementGuid>1d5ff889-6030-4403-bd3d-52483b8b3c64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mantine-rybb1xhle']</value>
      <webElementGuid>950dc3cf-f00e-4d04-858a-e0116ab10472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/div[2]/div[2]/section/div/form/div[3]/div/input</value>
      <webElementGuid>8920acf1-cfa6-4a80-9304-4e9c30f5b7d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>93761620-7641-49e3-8386-9056a300a4df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'test123@yopmail.com' and @id = 'mantine-rybb1xhle' and @type = 'text']</value>
      <webElementGuid>a2f05989-af03-4a2f-96d7-ba4f42b174fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
