<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_mantine-gleiszynf</name>
   <tag></tag>
   <elementGuidId>51482c4d-5eeb-4ac3-97d0-dddd48738ab5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mantine-gleiszynf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mantine-gleiszynf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64153c28-4454-4cb7-a981-95ede1a6b8bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>test123@yopmail.com</value>
      <webElementGuid>a51e2dc9-c6b3-4885-9048-94a6914c46b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mantine-gleiszynf</value>
      <webElementGuid>fff85d34-329c-45c5-b8f4-7fd64ad76b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d9f72a14-92a3-4949-bf25-984cf91d7404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>55650aaa-e530-49dd-83d4-e6808670bd2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-TextInput-defaultVariant mantine-TextInput-input mantine-TextInput-disabled mantine-1xoment</value>
      <webElementGuid>0546b74e-03b6-43f6-9658-4599bb230c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-gleiszynf&quot;)</value>
      <webElementGuid>4546bc60-42f4-42be-b1bc-1fdb28bc2fdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mantine-gleiszynf']</value>
      <webElementGuid>598c2185-91f9-44fa-9b6e-216371a18b40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/div[2]/div[2]/section/div/form/div[3]/div/input</value>
      <webElementGuid>b9a80013-88c1-4273-8da0-cf5b4904a0fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>e2c6b5ca-414e-4881-b48c-c27f6d73206e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'test123@yopmail.com' and @id = 'mantine-gleiszynf' and @type = 'text']</value>
      <webElementGuid>b5018b26-9f39-4618-87ad-59a58699cfd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
